# Generated by Django 4.2.3 on 2023-10-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                ("qsid", models.AutoField(primary_key=True, serialize=False)),
                ("set_name", models.CharField(max_length=30, unique=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensitiveWord",
            fields=[
                (
                    "word",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("register_date", models.DateField(auto_now_add=True)),
                ("profile_photo", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("tid", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=30, unique=True)),
                ("create_date", models.DateField(auto_now_add=True)),
                ("profile_photo", models.BinaryField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetHistory",
            fields=[
                ("shid", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField()),
                (
                    "qsid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.questionset",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSetPerm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "qsid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.questionset",
                    ),
                ),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questionset",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
        migrations.CreateModel(
            name="QuestionHistory",
            fields=[
                ("qhid", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.CharField(max_length=400)),
                ("score", models.FloatField()),
                (
                    "shid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.sethistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("qid", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=400)),
                ("answer", models.CharField(max_length=400)),
                ("score", models.FloatField()),
                ("serial_num", models.IntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
                (
                    "qsid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.questionset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=300)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="User.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="User.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
                (
                    "qsid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.questionset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReUserTeam",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("is_admin", models.BooleanField()),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.team"
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("uid", "tid")},
            },
        ),
        migrations.CreateModel(
            name="MonitorRelation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.team"
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("uid", "tid")},
            },
        ),
    ]
