# Generated by Django 4.2.3 on 2023-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_name",
            field=models.CharField(default="", max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MonitorRelation",
        ),
    ]
