# Generated by Django 4.2.3 on 2023-11-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_exam_exam_name_delete_monitorrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.AddField(
            model_name="questionset",
            name="profile_photo",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.JSONField(),
        ),
    ]
