# Generated by Django 4.2.3 on 2023-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_post_title_post_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionset",
            name="introduction",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="introduction",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
