# Generated by Django 4.2.3 on 2023-11-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0006_questionset_introduction_team_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=30)),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.team"
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
