# Generated by Django 4.2.3 on 2023-11-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_alter_post_update_time_joinrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "qsid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.questionset",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
