# Generated by Django 4.1 on 2023-12-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0008_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionhistory",
            name="qid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionhistory",
            name="uid",
            field=models.ForeignKey(
                default=7, on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
            preserve_default=False,
        ),
    ]
