# Generated by Django 4.2.3 on 2023-12-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0009_questionhistory_qid_questionhistory_uid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("uid", "qsid")},
        ),
    ]
