# Generated by Django 4.2.3 on 2023-12-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0011_entry"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["title"], name="User_post_title_3e87ec_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_name"], name="User_team_team_na_2edea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_name"], name="User_user_user_na_cee7d8_idx"
            ),
        ),
    ]
